# Generated by Django 4.2.4 on 2023-09-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='status',
            field=models.CharField(max_length=80),
        ),
    ]
